version: '2.4'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

  server:
    image: judge0/judge0:1.13.1
    restart: always
    ports:
      - "2358:2358"
    privileged: true
    cgroupns: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0-password
      POSTGRES_DB: judge0
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  worker:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    restart: always
    privileged: true
    cgroupns: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0-password
      POSTGRES_DB: judge0
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data: